<?php
require_once 'includes/global_variables.inc';
require_once 'includes/select_options.inc';

function products_comparison_init(){
  $mpath = drupal_get_path('module', 'products_comparison');
  drupal_add_js($mpath . '/js/comparison_slider.js');
}


function products_comparison_block_info() {
  $blocks = array();
  $blocks['products_comparison_block'] = array(
    'info' => t('Comparison Module'),
  );
  return $blocks;
}

function products_comparison_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'products_comparison_block':
     $block['content'] = products_comparison_main_content(); // set the content of the block to our products_comparison_main_content
     break;
  }
  return $block;
}


function products_comparison_main_content(){
  global $platforms, $firstyears_array, $tiles_array, $fname_postf, $fname_sensor;                                                             
  global $datadir, $datadir2;
  global $defyear;
  global $base_url;
  global $metsis_conf;
//
  $scr_name = $base_url ."/comparison";
//
//  # Initialize and find defaults depending on products 
  if(isset($_GET["tile"])){
     $tile = $_GET["tile"];
  }else{
     $tile = $tiles_array[0];
  }

  if(isset($_GET["pr1"])){
     $pr1 = $_GET["pr1"];
  }else{
     $pr1 = "None";
  }

  if(isset($_GET["pr2"])){
     $pr2 = $_GET["pr2"];
  }else{
     $pr2 = "None";
  }

  if(isset($_GET["action"])){
     $action = $_GET["action"];
  }else{
     $action = "";
  }

  $prinfo = array(array(array("YYYY", "MM","DD", "THHMMSS"), "None","None", array(68, 10)));
  $query_res = [];
  if ($tile !== "None"){
     //extract prinfo
     $fields = "id, mmd_data_access_resource, mmd_geographic_extent_rectangle_north, mmd_geographic_extent_rectangle_south, mmd_geographic_extent_rectangle_east, mmd_geographic_extent_rectangle_west";
     $query_prd = 'full_text:S2*'.$tile.'*';
     $con = new HttpConnection(SOLR_SERVER_IP, SOLR_SERVER_PORT);
     $res = $con->get('/solr/'.SOLR_CORE_PARENT.'/select', array("q" =>$query_prd, "start" => 0, "rows" => 100000, "wt" => "json", "fl" => $fields,));
     $query_res = json_decode($res['body'], true);
     $count = 1; 
     foreach ($query_res['response']['docs'] as $doc) {
        if (preg_match("/OPER/", $doc['id'])){
           $time_string = explode('_',$doc['id'],12)[7];
        }else{
           $time_string = explode('_',$doc['id'],7)[6];
        }
        $id = $doc['id'];
        $address = $doc['mmd_data_access_resource'][1];
        $address = json_decode("{".$address."}",true)['OGC WMS'];
        $north = $doc['mmd_geographic_extent_rectangle_north'];
        $south = $doc['mmd_geographic_extent_rectangle_south'];
        $east = $doc['mmd_geographic_extent_rectangle_east'];
        $west = $doc['mmd_geographic_extent_rectangle_west'];
        $ayear = substr($time_string, 0, 4);
        $amonth = substr($time_string, 4, 2); 
        $aday = substr($time_string, 6, 2);
        $atime = substr($time_string, 8, 7);
        $date = array($ayear,$amonth, $aday, $atime);
        $latlon = array(($south+$north)/2, ($east+$west)/2);
        $prinfo[$count] = array($date, $id, $address, $latlon);
        $count = $count + 1; 
     }
     sort($prinfo);
  }

  #call the function creating the selection options
  $selection_out = [];
  $selection_out = select_image($scr_name,$pr1,$pr2,$prinfo,$tile,$action,$tiles_array);
  $out = $selection_out[0];  
  $address1 = $selection_out[1];  
  $address2 = $selection_out[2];  
  $latlon1 = $selection_out[3];  
  $latlon2 = $selection_out[4];  

  $build_path1 = "null";
  $build_path2 = "null";
  $zoom = 2;
  $ll = $latlon1;
  if ($pr1 !== 'None'){ 
     $build_path1 = '"'.$address1.'"'; 
     $zoom = 6;
  }
  if ($pr2 !== 'None'){ 
     $build_path2 = '"'.$address2.'"'; 
     $zoom = 6;
     $ll = $latlon2;
  }

  $id_j1 = '"'.$pr1.'"';
  $id_j2 = '"'.$pr2.'"';

return $out . '

<!doctype html>                                                                                                                                                                                                         
<html lang="en">                                                                                                                                                                                                        
  <head>                                                                                                                                          
    <link rel="stylesheet" href="/sites/satellittdata.metsis.met.no/libraries/openlayers3/css/ol.css" type="text/css">
    <link rel="stylesheet" href="/sites/satellittdata.metsis.met.no/libraries/openlayers3/apidoc/styles/bootstrap.min.css">
    <link rel="stylesheet" href="/sites/satellittdata.metsis.met.no/libraries/ol3-layerswitcher/src/ol3-layerswitcher.css">
    <script src="/sites/satellittdata.metsis.met.no/libraries/openlayers3/build/ol.js" type="text/javascript"></script>
    <script src="/sites/all/modules/jquery_update/replace/jquery/1.10/jquery.min.js"></script>
    <script src="/sites/satellittdata.metsis.met.no/libraries/openlayers3/apidoc/scripts/bootstrap.min.js"></script>
    <script src="/sites/satellittdata.metsis.met.no/libraries/ol3-layerswitcher/src/ol3-layerswitcher.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.2.1/proj4.js"></script>
    <script type="text/javascript">
      prod_id1 = '.$build_path1.';
      prod_id2 = '.$build_path2.';
      id1 = '.$id_j1.';
      id2 = '.$id_j2.';
      lat = '.$ll[0].';
      lon = '.$ll[1].';
      zoomv = '.$zoom.';
    </script>
<style>
      .map {
        /*height: 500px;*/
        width: 100%;
        margin: auto;
        border: 2px solid #c8c7c7;
      }

.drop-selection {
   height: 30px !important;
   display: inline !important;
   margin-right: auto;
   margin-left: auto;
}

.table, th, td, tr {
   border: 1px solid #c8c7c7;
}

#swipe::-moz-range-thumb {
    align: center;
    width: 15px;
    height: 15px;
    border-radius: 50%; 
    background: #81b6da;
    border-color: #000;
    border-width: 1px;
    cursor: pointer;
}


    </style>
  </head>
  <body>
    <div id="map" class="map" >
    <input id="swipe" type="range" style="width: 100%; margin-bottom:10px; margin: 0px">
    <script type="text/javascript" src="/sites/satellittdata.metsis.met.no/modules/products_comparison/js/comparison_slider.js"></script>
  </body>
</html>
';
}
?>
