products_comparison:
  path: '/services/comparison'
  defaults:
    _controller: '\Drupal\products_comparison\Controller\ProductsComparisonController::render'
    _title_callback: '\Drupal\products_comparison\Controller\ProductsComparisonController::getTitle'
  requirements:
    _permission: 'access content'

products_comparison.date:
  path: '/services/comparison/date/{tile}'
  defaults:
    _controller: '\Drupal\products_comparison\Controller\ProductsComparisonController::getProductTime'
    _title: 'Products ajax callback'
  options:
    query:
      cloud: "None"
  requirements:
    _permission: 'access content'

metsis.services:
  path: '#'
  defaults:
    _title: 'Services'
  requirements:
    _permission: 'access content'

products_comparison.admin_config_form:
  path: '/admin/config/metsis/products_comparison'
  defaults:
    _form: '\Drupal\products_comparison\Form\ProductsComparisonConfigurationForm'
    _title: 'Sentinel-2 products comparison configuration'
  requirements:
    _permission: 'administer site configuration'
  options:
    _admin_route: TRUE

system.admin_config_metno:
  path: '/admin/config/metno'
  defaults:
    _controller: '\Drupal\system\Controller\SystemController::systemAdminMenuBlockPage'
    _title: 'METNO'
    description: 'METNO Specific configuraton'
  requirements:
    _permission: 'administer site configuration'

system.admin_config_metsis:
  path: '/admin/config/metsis'
  defaults:
    _controller: '\Drupal\system\Controller\SystemController::systemAdminMenuBlockPage'
    _title: 'METSIS'
    description: 'METSIS Specific configuraton'
  requirements:
    _permission: 'administer site configuration'
