<?php


use Drupal\Core\Routing\RouteMatchInterface;

function products_comparison_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
    // Main module help for the metsis_search module.
    /** TODO: Read help from module's README.md */
    case 'help.page.products_comparison':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Products Comparison') . '</p>';
      return $output;

    default:
  }
}


// Implements hook_theme()
function products_comparison_theme( $existing, $type, $theme, $path ){
    return [
        'products_comparison-template' => [
            'render element' => 'container', // To render a simple container element
            'template' => 'products_comparison', // My template file name
            'variables' => [
                'site_name' => "Default",
                'tiles' => null,
                'helptext' => '',
              ],
        ],
    ];
}
