products_comparison.configuration:
  type: config_object
  label: 'Sentinel-2 products comparison configuration'
  mapping:
    helptext:
      label: 'Help text to be displayed under the map'
      type: text_format
    langcode:
      type: string
      label: 'Language code'
    lat:
    type: int
    label: 'Initial centre latitude for map'
    lon:
      type: int
      label: 'Initial centre longitude for map'
    defzoom:
      type: int
      label: 'Initial zoom level for map'
    rows:
      type: int
      label: 'Date rows to be returned'

